# Generated by Django 5.1 on 2024-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='profilepic',
            field=models.FileField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
