# Generated by Django 5.0.7 on 2024-09-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0004_userreg_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.FileField(blank=True, null=True, upload_to='post_pics/')),
                ('description', models.TextField(blank=True, null=True)),
                ('likes_count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.userreg')),
            ],
        ),
    ]
