# Generated by Django 5.0.7 on 2024-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0006_commentsectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='likes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
