# Generated by Django 5.0.7 on 2024-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0007_alter_postmodel_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='apk.userreg'),
        ),
    ]
