# Generated by Django 5.0.6 on 2024-09-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0008_remove_postmodel_user_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='liked_users',
            field=models.ManyToManyField(null=True, related_name='likes_count', to='apk.userreg'),
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apk.userreg'),
            preserve_default=False,
        ),
    ]
