# Generated by Django 5.0.6 on 2024-09-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0009_postmodel_liked_users_remove_postmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='liked_users',
            field=models.ManyToManyField(null=True, related_name='liked_posts', to='apk.userreg'),
        ),
    ]
